package testing;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;

public class TinhteWritePostTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String args[]) {
		/*
		 * if (System.getProperty("webdriver.firefox.bin") == null) { // Replace with
		 * your Firefox 46 path System.setProperty("webdriver.firefox.bin",
		 * "C:\\Program Files (x86)\\Mozilla Firefox 46\\firefox.exe"); }
		 */
		if (System.getProperty("webdriver.chrome.driver") == null) {
			System.setProperty("webdriver.chrome.driver", "C:\\Program Files (x86)\\Driver\\chromedriver.exe");
		}
		JUnitCore junit = new JUnitCore();
		junit.addListener(new TextListener(System.out));
		Result result = junit.run(TinhteWritePostTest.class); // Replace your class name
		if (result.getFailureCount() > 0) {
			System.out.println("Test failed.");
			System.exit(1);
		} else {
			System.out.println("Test finished successfully.");
			System.exit(0);
		}
	}

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testcase1() throws InterruptedException {
		// Test name: TC-001-001
		String data = "Nên làm gì vào buổi sáng cuối tuần?";
		// 1. Open

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2. Click VietBai
		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();
		// 3. Click textbox
		driver.findElement(By.className(".thread-editor-textarea")).click();
		// 4. Send data
		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);
		// 5. Click DangBai
		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();
		// 6. Check
		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase2() throws InterruptedException {
		// Test name: TC-001-002
		String data = "๖ۣۜNên làm ğì vào buổi sáng cuốḭ tuần?";

		// 1. Open
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2. Click VietBai
		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();
		// 3. Click textbox
		driver.findElement(By.className(".thread-editor-textarea")).click();
		// 4. Send data
		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);
		// 5. Click DangBai
		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();
		// 6. Check
		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase3() throws InterruptedException {
		// Test name: TC-001-003
		String data = "Ngắn";

		// 1. Open
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2. Click VietBai
		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();
		// 3. Click textbox
		driver.findElement(By.className(".thread-editor-textarea")).click();
		// 4. Send data
		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);
		// 5. Click DangBai
		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();
		// 6. Get text
		String notification = driver.findElement(By.className(".jsx-1783754700 text")).getText();

		String note = "Bạn phải gõ dài hơn 10 kí tự mới được nhé :D";
		// 7. Check
		assertEquals(data, notification);

		driver.close();
	}

	@Test
	public void testcase4() throws InterruptedException {
		// Test name: TC-001-004
		String data = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".thread-editor-textarea")).click();

		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase5() throws InterruptedException {
		// Test name: TC-001-005
		String data = "Đây là bài post có background";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".thread-editor-textarea")).click();

		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);
		// Click tuy chinh BackGround
		driver.findElement(By.className(".jsx-1783754700 thread-background-switch")).click();
		// Click chon BackGround
		driver.findElement(By.className(".jsx-1783754700 thread-background-image")).click();

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase6() throws InterruptedException {
		// Test name: TC-001-006
		String data = "Đây là bài post có background";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".thread-editor-textarea")).click();

		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);

		driver.findElement(By.className(".jsx-1783754700 thread-background-switch")).click();

		driver.findElement(By.className(".jsx-1783754700 thread-background-image")).click();

		driver.findElement(By.className(".jsx-1783754700 thread-background-image")).click();

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase7() throws InterruptedException {
		// Test name: TC-001-007
		String data = "Đây là bài post có kèm link";
		String link = "facebook.com/dat070699";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".thread-editor-textarea")).click();

		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);
		// Click chon chen link
		driver.findElement(By.className(".jsx-1783754700 thread-background-switch link-sharing")).click();
		// Send link
		driver.findElement(By.className(".jsx-1783754700 link-input")).sendKeys(link);

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase8() throws InterruptedException {
		// Test name: TC-001-008
		String data = "Đây là bài post có kèm link";
		String link = "canvjkasnckj.com";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".thread-editor-textarea")).click();

		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);

		driver.findElement(By.className(".jsx-1783754700 thread-background-switch link-sharing")).click();

		driver.findElement(By.className(".jsx-1783754700 link-input")).sendKeys(link);

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase9() throws InterruptedException {
		// Test name: TC-001-009
		String data = "Đây là bài post có kèm ảnh";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".thread-editor-textarea")).click();

		driver.findElement(By.className(".thread-editor-textarea")).sendKeys(data);
		// Chon up anh
		driver.findElement(By.className(".jsx-1783754700 file-upload-btn")).click();
		// Up anh
		driver.findElement(By.className(".jsx-3297489929 image-picker-loading box center-xs middle-xs")).click();

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals(data, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase12() throws InterruptedException {
		// Test name: TC-001-012
		String data = "Đây là fact mới của tôi";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 fact-home-button")).click();
		// Click Tao fact moi
		driver.findElement(By.className(".thread-editor-textarea createTinhteFact")).click();

		driver.findElement(By.className(".thread-editor-textarea createTinhteFact")).sendKeys(data);

		String name = driver.findElement(By.className(".jsx-3049229214 preview-view-author")).getText();

		driver.findElement(By.className(".jsx-1783754700 publish-btn disable")).click();

		assertEquals("DatHuynh0706", name);

		driver.close();
	}

	@Test
	public void testcase13() throws InterruptedException {
		// Test name: TC-001-013
		String title = "Bài dài đầu tiên của tôi";
		String data = "Chúng ta nên bắt đầu viết bài này như thế nào";
		String tag = "baiviet,dautien,baidai";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();
		// Click chon Bai dai
		driver.findElement(By.className(".jsx-1783754700 btn category-selector-switch")).click();

		driver.findElement(By.className(".title-input")).click();

		driver.findElement(By.className(".title-input")).sendKeys(title);

		driver.findElement(By.className(".jsx-1329374219 editor")).click();

		driver.findElement(By.className(".jsx-1329374219 editor")).sendKeys(data);

		driver.findElement(By.className(".jsx-1329374219 tag-input")).click();

		driver.findElement(By.className(".jsx-1329374219 tag-input")).sendKeys(tag);

		driver.findElement(By.className(".jsx-1329374219 toolbar-save-button")).click();

		driver.findElement(By.className(".jsx-4275400642 confirm-button")).click();

		assertEquals(title, driver.getTitle());

		driver.close();
	}

	@Test
	public void testcase15() throws InterruptedException {
		// Test name: TC-001-015
		String data = "Chúng ta nên bắt đầu viết bài này như thế nào";
		String tag = "baiviet,dautien,baidai";

		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);

		driver.findElement(By.className(".jsx-1783754700 blue-switch header-mode")).click();

		driver.findElement(By.className(".jsx-1783754700 btn category-selector-switch")).click();

		driver.findElement(By.className(".jsx-1329374219 editor")).click();

		driver.findElement(By.className(".jsx-1329374219 editor")).sendKeys(data);

		driver.findElement(By.className(".jsx-1329374219 tag-input")).click();

		driver.findElement(By.className(".jsx-1329374219 tag-input")).sendKeys(tag);

		driver.findElement(By.className(".jsx-1329374219 toolbar-save-button")).click();

		driver.findElement(By.className(".jsx-4275400642 confirm-button")).click();
		// Get thong bao loi
		String note = driver.findElement(By.className(".jsx-1329374219 error-message")).getText();

		assertEquals("Error: title: Please enter a valid title.", note);

		driver.close();
	}
}