package testing;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;

public class TinhteMessageTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String args[]) {
		if (System.getProperty("webdriver.chrome.driver") == null) {
			System.setProperty("webdriver.chrome.driver", "C:\\Users\\feli9\\Downloads\\chromedriver.exe");
		}
		JUnitCore junit = new JUnitCore();
		junit.addListener(new TextListener(System.out));
		Result result = junit.run(TinhteMessageTest.class);
		if (result.getFailureCount() > 0) {
			System.out.println("Test failed.");
			System.exit(1);
		} else {
			System.out.println("Test finished successfully.");
			System.exit(0);
		}
	}

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	// tạo tin nhắn đơn giản
	public void testcase1() throws InterruptedException {
		String content = "Hi!";
		// mở trang tinh tế
		driver.get("https://tinhte.vn/");
		// click vào nút đăng nhập
		driver.findElement(By.cssSelector(".jsx-1306406219")).click();
		// nhập username
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");
		// nhập password
		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();
		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();
		// nhấn vào hộp thư
		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		// chọn xem tất cả
		driver.findElement(By.linkText("Xem tất cả")).click();
		driver.findElement(By.cssSelector(".topCtrl span")).click();
		// nhập người nhận
		driver.findElement(By.id("ctrl_recipients")).click();
		driver.findElement(By.id("ctrl_recipients")).sendKeys("AnhTuu1024");
		// nhập tiêu đề
		driver.findElement(By.id("ctrl_title")).click();
		driver.findElement(By.id("ctrl_title")).sendKeys("Trò chuyện 1");
		// nhập nội dung
		driver.switchTo().frame(0);
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.cssSelector("body")).sendKeys(content);
		driver.switchTo().defaultContent();
		// gửi
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(3) .primary")).click();
		Thread.sleep(3000);
		String result = driver.findElement(By.cssSelector(".baseHtml")).getText();
		System.out.println(result);
		assertEquals(content, result);
		driver.close();
	}

	@Test
	// tạo tin nhắn thiếu tên ngư�?i nhận
	public void testcase3() throws InterruptedException {
		String content = "Tham gia:\nPlease enter at least one valid recipient.";
		driver.get("https://tinhte.vn/");
		driver.findElement(By.cssSelector(".jsx-1306406219")).click();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");
		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();
		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();
		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.linkText("Xem tất cả")).click();
		driver.findElement(By.cssSelector(".topCtrl span")).click();
		driver.findElement(By.id("ctrl_title")).click();
		driver.findElement(By.id("ctrl_title")).sendKeys("Trò chuyện 1");

		driver.switchTo().frame(0);
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.cssSelector("body")).sendKeys("Hi!");
		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(3) .primary")).click();
		Thread.sleep(1000);

		String result = driver.findElement(By.cssSelector(".baseHtml")).getText();
		System.out.println(result);
		assertEquals(content, result);
		driver.close();

	}

	@Test
	// tạo tin nhắn thiếu tên chủ đ�?
	public void testcase4() throws InterruptedException {
		String content = "Tiêu đề:\nPlease enter a valid title.";
		driver.get("https://tinhte.vn/");

		driver.findElement(By.cssSelector(".jsx-1306406219")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();

		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.linkText("Xem tất cả")).click();
		driver.findElement(By.cssSelector(".topCtrl span")).click();

		driver.findElement(By.id("ctrl_recipients")).click();
		driver.findElement(By.id("ctrl_recipients")).sendKeys("AnhTuu1024");

		driver.switchTo().frame(0);
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.cssSelector("body")).sendKeys("Hi!");
		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(3) .primary")).click();
		Thread.sleep(1000);
		String result = driver.findElement(By.cssSelector(".baseHtml")).getText();
		System.out.println(result);
		assertEquals(content, result);
		driver.close();
	}

	@Test
	// tạo tin nhắn thiếu nội dung
	public void testcase5() throws InterruptedException {
		String content = "Please enter a valid message.";
		driver.get("https://tinhte.vn/");

		driver.findElement(By.cssSelector(".jsx-1306406219")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();

		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.linkText("Xem tất cả")).click();
		driver.findElement(By.cssSelector(".topCtrl span")).click();

		driver.findElement(By.id("ctrl_recipients")).click();
		driver.findElement(By.id("ctrl_recipients")).sendKeys("AnhTuu1024");
		driver.findElement(By.id("ctrl_title")).click();
		driver.findElement(By.id("ctrl_title")).sendKeys("Trò chuyện 1");

		driver.switchTo().frame(0);

		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(3) .primary")).click();
		Thread.sleep(1000);
		String result = driver.findElement(By.cssSelector(".baseHtml")).getText();
		System.out.println(result);
		assertEquals(content, result);
		driver.close();
	}

	@Test
	// gửi tin nhắn cho thành viên không tồn tại
	public void testcase6() throws InterruptedException {
		String content = "Tham gia:\nThe following recipients could not be found: AnhTuuu1024.";
		driver.get("https://tinhte.vn/");

		driver.findElement(By.cssSelector(".jsx-1306406219")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();

		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.linkText("Xem tất cả")).click();
		driver.findElement(By.cssSelector(".topCtrl span")).click();

		driver.findElement(By.id("ctrl_recipients")).click();
		driver.findElement(By.id("ctrl_recipients")).sendKeys("AnhTuuu1024");
		driver.findElement(By.id("ctrl_title")).click();
		driver.findElement(By.id("ctrl_title")).sendKeys("Trò chuyện 1");

		driver.switchTo().frame(0);
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.cssSelector("body")).sendKeys("Hi!");
		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(3) .primary")).click();
		Thread.sleep(1000);
		String result = driver.findElement(By.cssSelector(".baseHtml")).getText();
		System.out.println(result);
		assertEquals(content, result);
		driver.close();
	}

	@Test
	// trả l�?i tin nhắn
	public void testcase9() throws InterruptedException {
		driver.get("https://tinhte.vn/");

		driver.findElement(By.cssSelector(".jsx-1306406219")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();

		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.cssSelector(".jsx-756775732:nth-child(1) > .jsx-3853293736 .title")).click();

		driver.switchTo().frame(0);
		driver.findElement(By.cssSelector("body")).click();
		driver.findElement(By.cssSelector("body")).sendKeys("Alo alo đang ở đâu vậy");
		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector(".primary:nth-child(2)")).click();
		Thread.sleep(1000);
		driver.close();
	}

	@Test
	// trả l�?i tin nhắn thiếu nội dung
	public void testcase11() throws InterruptedException {
		String content = "Có lỗi hoặc lưu ý:\nPlease enter a valid message.";
		driver.get("https://tinhte.vn/");

		driver.findElement(By.cssSelector(".jsx-1306406219")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();

		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.cssSelector(".jsx-756775732:nth-child(1) > .jsx-3853293736 .title")).click();

		driver.switchTo().frame(0);

		driver.switchTo().defaultContent();
		driver.findElement(By.cssSelector(".primary:nth-child(2)")).click();
		Thread.sleep(1000);
		;
		String result = driver.findElement(By.cssSelector(".errorOverlay")).getText();
		System.out.println(result);
		assertEquals(content, result);
		driver.close();
	}

	@Test
	// Sửa tiêu đ�? cuộc hội thoại
	public void testcase13() throws InterruptedException {

		driver.get("https://tinhte.vn/");

		driver.findElement(By.cssSelector(".jsx-1306406219")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).click();

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(2) #ctrl_pageLogin_login")).sendKeys("anhtus123");

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password")).click();

		driver.findElement(By.cssSelector("#ctrl_pageLogin_registered_Disabler > #ctrl_pageLogin_password"))
				.sendKeys("123456");

		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .button")).click();

		driver.findElement(By.cssSelector(".jsx-724576068 > g > g:nth-child(2) > path")).click();
		driver.findElement(By.cssSelector(".jsx-756775732:nth-child(1) > .jsx-3853293736 .title")).click();

		driver.findElement(By.linkText("Sửa tin nhắn")).click();
		driver.findElement(By.id("ctrl_title")).click();
		driver.findElement(By.id("ctrl_title")).sendKeys("Con mèo");
		Thread.sleep(1000);
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(4) .primary")).click();
		driver.close();
	}

}