package testing;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.junit.runner.Result;

public class TinhteSearchTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String args[]) {
		/*
		 * if (System.getProperty("webdriver.firefox.bin") == null) { // Replace with
		 * your Firefox 46 path System.setProperty("webdriver.firefox.bin",
		 * "C:\\Program Files (x86)\\Mozilla Firefox 46\\firefox.exe"); }
		 */
		if (System.getProperty("webdriver.chrome.driver") == null) {
			System.setProperty("webdriver.chrome.driver", "C:\\Users\\leson\\Downloads\\chromedriver.exe");
		}
		JUnitCore junit = new JUnitCore();
		junit.addListener(new TextListener(System.out));
		Result result = junit.run(TinhteSearchTest.class); // Replace your class name
		if (result.getFailureCount() > 0) {
			System.out.println("Test failed.");
			System.exit(1);
		} else {
			System.out.println("Test finished successfully.");
			System.exit(0);
		}
	}

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testcase1() throws InterruptedException {
		// Test name: testcase_1
		String data = "điện thoại";
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 3 | click | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).click();
		// 4 | type | css=.search-textbox | điện thoại
		driver.findElement(By.cssSelector(".search-textbox")).sendKeys(data);
		// 5 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 6 | checkResult | |
		assertEquals("Kết quả tìm kiếm \"" + data + "\" | Tinhte.vn", driver.getTitle());
		// 7 | close | |
		driver.close();
	}

	@Test
	public void testcase2() throws InterruptedException {
		// Test name: testcase_2
		String data = "điễn thoải";
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 3 | click | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).click();
		// 4 | type | css=.search-textbox | điễn thoải
		driver.findElement(By.cssSelector(".search-textbox")).sendKeys(data);
		// 5 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 6 | checkResult | |
		assertEquals("Kết quả tìm kiếm \"" + data + "\" | Tinhte.vn", driver.getTitle());
		// 7 | close | |
		driver.close();
	}

	@Test
	public void testcase3() throws InterruptedException {
		// Test name: testcase_3
		String data = "[ß]ui_ðoi™";
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 3 | click | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).click();
		// 4 | type | css=.search-textbox | [ß]ui_ðoi™
		driver.findElement(By.cssSelector(".search-textbox")).sendKeys(data);
		// 5 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 6 | checkResult | |
		assertEquals("Kết quả tìm kiếm \"" + data + "\" | Tinhte.vn", driver.getTitle());
		// 7 | close | |
		driver.close();
	}

	@Test
	public void testcase4() throws InterruptedException {
		// Test name: testcase_4
		String data = "    ";
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2 | click | css=.search-icon |
		driver.findElement(By.cssSelector(".search-icon")).click();
		// 3 | click | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).click();
		// 4 | type | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).sendKeys(data);
		// 5 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 6 | checkResult | |
		assertEquals("Thông báo | Tinhte.vn", driver.getTitle());
		// 7 | close | |
		driver.close();
	}

	@Test
	public void testcase5() throws InterruptedException {
		// Test name: testcase_5
		String data = "sagfghbvmgwsczvf";
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 3 | click | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).click();
		// 4 | type | css=.search-textbox | sagfghbvmgwsczvf
		driver.findElement(By.cssSelector(".search-textbox")).sendKeys(data);
		// 5 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 6 | checkResult | |
		assertEquals("Tinhte.vn", driver.getTitle());
		WebElement result = driver.findElement(By.cssSelector(".messageBody"));
		assertEquals("Không có kết quả được tìm thấy.", result.getText());
		// 7 | close | |
		driver.close();
	}

	@Test
	public void testcase6() throws InterruptedException {
		// Test name: testcase_6
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://tinhte.vn/");
		Thread.sleep(1000);
		// 2 | click | css=.search-icon |
		driver.findElement(By.cssSelector(".search-icon")).click();
		// 3 | click | css=.search-textbox |
		driver.findElement(By.cssSelector(".search-textbox")).click();
		// 4 | click | css=.jsx-2615189454 > svg |
		driver.findElement(By.cssSelector(".jsx-2615189454 > svg")).click();
		// 5 | checkResult | |
		assertEquals("Cộng đồng Khoa học & Công nghệ | Tinh tế", driver.getTitle());
		// 6 | close | |
		driver.close();
	}

	@Test
	public void testcase7() throws InterruptedException {
		// Test name: testcase_7
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 4 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Tìm kiếm | Tinhte.vn", driver.getTitle());
		// 5 | close | |
		driver.close();
	}

	@Test
	public void testcase8() throws InterruptedException {
		// Test name: testcase_8
		String data = "điện thoại";
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | type | id=ctrl_keywords | điện thoại
		driver.findElement(By.id("ctrl_keywords")).sendKeys(data);
		// 4 | click | id=ctrl_title_only |
		driver.findElement(By.id("ctrl_title_only")).click();
		// 5 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 6 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Kết quả tìm kiếm \"" + data + "\" | Tinhte.vn", driver.getTitle());
		// 7 | close | |
		driver.close();
	}

	@Test
	public void testcase9() throws InterruptedException {
		// Test name: testcase_9
		String data = "điện thoại";
		String userName = "cuhiep";
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | type | id=ctrl_keywords | điện thoại
		driver.findElement(By.id("ctrl_keywords")).sendKeys(data);
		// 4 | click | id=ctrl_users |
		driver.findElement(By.id("ctrl_users")).click();
		// 5 | type | id=ctrl_users | cuhiep
		driver.findElement(By.id("ctrl_users")).sendKeys(userName);
		// 6 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 7 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Kết quả tìm kiếm \"" + data + "\" | Tinhte.vn", driver.getTitle());
		// 8 | close | |
		driver.close();
	}

	@Test
	public void testcase10() throws InterruptedException {
		// Test name: testcase_10
		String data = "điện thoại";
		String userName = "xacvb";
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | type | id=ctrl_keywords | điện thoại
		driver.findElement(By.id("ctrl_keywords")).sendKeys(data);
		// 4 | click | id=ctrl_users |
		driver.findElement(By.id("ctrl_users")).click();
		// 5 | type | id=ctrl_users | xacvb
		driver.findElement(By.id("ctrl_users")).sendKeys(userName);
		// 6 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 7 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Tìm kiếm | Tinhte.vn", driver.getTitle());
		// 8 | close | |
		driver.close();
	}

	@Test
	public void testcase11() throws InterruptedException {
		// Test name: testcase_11
		String data = "điện thoại";
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | type | id=ctrl_keywords | điện thoại
		driver.findElement(By.id("ctrl_keywords")).sendKeys(data);
		// 4 | click | id=ctrl_date |
		driver.findElement(By.id("ctrl_date")).click();
		// 5 | click | id=calprev |
		driver.findElement(By.id("calprev")).click();
		// 6 | click | linkText=14 |
		driver.findElement(By.linkText("14")).click();
		// 7 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 8 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Kết quả tìm kiếm \"điện thoại\" | Tinhte.vn", driver.getTitle());
		// 9 | close | |
		driver.close();
	}

	@Test
	public void testcase12() throws InterruptedException {
		// Test name: testcase_12
		String data = "điện thoại";
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | type | id=ctrl_keywords | điện thoại
		driver.findElement(By.id("ctrl_keywords")).sendKeys(data);
		// 4 | click | id=ctrl_date |
		driver.findElement(By.id("ctrl_date")).click();
		// 5 | click | id=calnext |
		driver.findElement(By.id("calnext")).click();
		// 6 | click | linkText=16 |
		driver.findElement(By.linkText("16")).click();
		// 7 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 8 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Tìm kiếm | Tinhte.vn", driver.getTitle());
		// 9 | close | |
		driver.close();
	}

	@Test
	public void testcase13() throws InterruptedException {
		// Test name: testcase_13
		String data = "điện thoại";
		// Step # | name | target | value
		// 1 | open | https://tinhte.vn/search |
		driver.get("https://tinhte.vn/search");
		Thread.sleep(1000);
		// 2 | click | id=ctrl_keywords |
		driver.findElement(By.id("ctrl_keywords")).click();
		// 3 | type | id=ctrl_keywords | điện thoại
		driver.findElement(By.id("ctrl_keywords")).sendKeys(data);
		// 4 | removeSelection | id=ctrl_nodes | label=Các diễn đàn
		{
			WebElement dropdown = driver.findElement(By.id("ctrl_nodes"));
			dropdown.findElement(By.xpath("//option[. = 'Các diễn đàn']")).click();
		}
		// 5 | addSelection | id=ctrl_nodes | label=Thông tin - Sự kiện
		{
			WebElement dropdown = driver.findElement(By.id("ctrl_nodes"));
			dropdown.findElement(By.xpath("//option[. = 'Thông tin - Sự kiện']")).click();
		}
		// 6 | click | css=.ctrlUnit:nth-child(7) .button |
		driver.findElement(By.cssSelector(".ctrlUnit:nth-child(7) .button")).click();
		// 7 | checkResult | |
		Thread.sleep(1000);
		assertEquals("Kết quả tìm kiếm \"" + data + "\" | Tinhte.vn", driver.getTitle());
		// 8 | close | |
		driver.close();
	}
}